# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rose < Formula
  desc "A command line tool that allows you to treat files as sets of rows and perform set operations on them."
  homepage "https://github.com/suzaku/rose"
  version "0.0.8"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzaku/rose/releases/download/v0.0.8/rose_Mac_x86_64.tar.gz"
      sha256 "4bb3d032f51a64e12e3ffcf9a5b288d43449ac90d9df8bdccf450824aff1bd22"
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzaku/rose/releases/download/v0.0.8/rose_Mac_arm64.tar.gz"
      sha256 "2a5be5442057f996d0eef849a723fc6b0321b239a5de07a744ae433980903c4b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzaku/rose/releases/download/v0.0.8/rose_Linux_x86_64.tar.gz"
      sha256 "1c9c7bb8ff5342338a5d746f9d061730ce826d48e076f3fb762b0525594befd7"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/suzaku/rose/releases/download/v0.0.8/rose_Linux_armv6.tar.gz"
      sha256 "082ed6c1ac78e1af6e9dd13f7a9f88b73937ae58d6d0defaa5d839b97ad42f90"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzaku/rose/releases/download/v0.0.8/rose_Linux_arm64.tar.gz"
      sha256 "50ef0fc5ac0d44ffa43f6dce7d6506092df1627c91b7000d298fb850c3e7a19e"
    end
  end

  def install
    bin.install "rose"
    output = Utils.popen_read("#{bin}/rose completion bash")
    (bash_completion/"rose").write output
    output = Utils.popen_read("#{bin}/rose completion zsh")
    (zsh_completion/"_rose").write output
  end

  test do
    system "#{bin}/rose -v"
  end
end
